shop.net/shopstore/shopelements/urls.py
from django.urls import path
from .views import *

app_name='ecomapp'

urlpatterns = [
	path("add-to-cart-<int:pro_id>/", AddToCartView.as_view(), name="addtocart"),
    path("my-cart/", MyCartView.as_view(), name="mycart"),
    path("manage-cart/<int:cp_id>/", ManageCartView.as_view(), name="managecart"),
    path("empty-cart/", EmptyCartView.as_view(), name="emptycart"),
    path("checkout/", CheckoutView.as_view(), name="checkout"),
]

shop.net/shopstore/shopstore/urls.py
from django.contrib import admin
from django.urls import path, include
from shopelements import urls
from shopelements import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePageView, name='home'),
    path('about/', views.AboutPageView, name='about'),
    path('brand/', views.BrandPageView, name='brand'),
    path('specials/', views.SpecialsPageView, name='specials'),
    path('product/<int:pk>/', views.DetailPageView.as_view(), name='detail'),
    path('product/<int:pk>/comment/', views.comment,name='comment_url'),
    path('product/comment/update/<int:pk>/', views.CommentUpdatePageView.as_view(), name='comment_update'),
    path('search_venues/', views.search_venues, name='search-venues'),
    path('', include('shopelements.urls', namespace='ecomapp'))
]

shop.net/shopstore/shopelements/models.py
from django.db import models
import datetime
from django.urls import reverse

class Product(models.Model):
	name = models.CharField(max_length=50)
	text = models.TextField()
	firma = models.CharField(max_length=70)
	cost = models.PositiveIntegerField()
	COLOR_CHOICES = (
		("red", 'red'),
		("green", 'green'),
		("blue", 'blue'),
		("pink", 'pink'),
		("black", 'black'),
		("white", 'white'),
		("brown", 'brown'),
		("yellow", 'yellow')
	)
	colour = models.CharField(choices=COLOR_CHOICES, max_length=10, default='qizil')
	date = models.DateTimeField(auto_now=True)
	image = models.ImageField(upload_to='static/uploads/', null=True)
	YEAR_CHOICES = [(r,r) for r in range(1984, datetime.date.today().year+1)]
	made_year = models.IntegerField('year', choices=YEAR_CHOICES, default=datetime.datetime.now().year)

	def __str__(self):
		return self.name + '(' + self.firma + ')'
	class Meta:
		ordering = ['-cost']


class Comment(models.Model):
	fullname = models.CharField(max_length=50, null=True)
	text = models.TextField(null=True)
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	date = models.DateTimeField(auto_now=True)

	def get_absolute_url(self):
		return f'/product/{self.product.pk}/'
	class Meta:
		ordering = ['-date']

class Cart(models.Model):
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart: " + str(self.id)


class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return "Cart: " + str(self.cart.id) + " CartProduct: " + str(self.id)


ORDER_STATUS = (
    ("Order Received", "Order Received"),
    ("Order Processing", "Order Processing"),
    ("On the way", "On the way"),
    ("Order Completed", "Order Completed"),
    ("Order Canceled", "Order Canceled"),
)

METHOD = (
    ("Cash On Delivery", "Cash On Delivery"),
    ("Khalti", "Khalti"),
    ("Esewa", "Esewa"),
)


class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE, unique=True)
    ordered_by = models.CharField(max_length=200)
    shipping_address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=10)
    email = models.EmailField(null=True, blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    payment_method = models.CharField(
        max_length=20, choices=METHOD, default="Cash On Delivery")
    payment_completed = models.BooleanField(
        default=False, null=True, blank=True)

    def __str__(self):
        return "Order: " + str(self.id)

shop.net/shopstore/templates/about.html
{% extends 'base.html' %}
<!-- body -->

{% block title %} About {% endblock title %}

    {% block content %}
    <div class="loader_bg">
        <div class="loader"><img src="/static/images/loading.gif" alt="#" /></div>
    </div>
    <!-- end loader -->
    <!-- header -->

    <!-- end header -->
    <div class="brand_color">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="titlepage">
                        <h2>About</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- about -->
    <div class="about">
        <div class="container">
            <div class="row">
                <div class="col-xl-5 col-lg-5 col-md-5 co-sm-l2">
                    <div class="about_img">
                        <figure><img src="/static/images/about.png" alt="img" /></figure>
                    </div>
                </div>
                <div class="col-xl-7 col-lg-7 col-md-7 co-sm-l2">
                    <div class="about_box">
                        <span>Our Mobile Shop</span>
                        <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of It is a long established fact that a reader will be distracted by the </p>

                    </div>
                </div>
                <div class="col-xl-7 col-lg-7 col-md-7 co-sm-l2">
                    <div class="about_box_ ">
                        <span>Our Mobile Shop</span>
                        <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of It is a long established fact that a reader will be distracted by the </p>

                    </div>
                </div>
                <div class="col-xl-5 col-lg-5 col-md-5 co-sm-l2">
                    <div class="about_img">
                        <figure><img src="/static/images/about.png" alt="img" /></figure>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
    <!-- end about -->

    <!-- footer -->

    {% endblock content %}
    <!-- end footer -->
    <!-- Javascript files-->

shop.net/shopstore/templates/addtocart.html
{% extends 'base.html' %}
{% block title %} Added to Cart{% endblock title %}

{% block content %}

<div style="padding-top: 10%; padding-bottom: 10%; padding-left: 35%;">
	<h1>Product added to cart successfully!</h1>
</div>

<script type="text/javascript">
	alert('Added to cart')
</script>

{% endblock content %}

shop.net/shopstore/templates/base.html
{% load static %}

<!doctype html> 
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- mobile metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <!-- site metas -->
    <title>pomato</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- bootstrap css -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- style css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- Responsive-->
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <!-- fevicon -->
    <link rel="icon" href="{% static 'images/fevicon.png' %}" type="image/gif" />
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
    <!-- Tweaks for older IEs-->
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
    <!-- owl stylesheets -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <title>{% block title %} {% endblock title %}</title>
  </head>
  <body class="main-layout">
<style type="text/css">
.search {
    margin-bottom: auto;
    height: 50px;
    background-color: #fff;
    padding: 10px;
    border-right: 0 solid red;
    border-radius: 55px 0 0 55px;
}

.search-input {
    color: #6666;
    border: 0;
    outline: 0;
    background: none;
    width: 0;
    caret-color: transparent;
    line-height: 24px;
    transition: width 0.4s linear;
}

.search .search-input {
    padding-left: 10px;
    padding-top: 3px;
    width: 550px;
    caret-color: red;
    font-size: 15px;
    font-weight: 300;
    color: #666666;
    transition: width 0.4s linear
}

.search:hover>.search-icon {
    background: red;
    color: #fff
}

.search-icon {
    height: 30px;
    width: 30px;
    float: right;
    display: flex;
    justify-content: center;
    align-items: center;
    color: white;
    background-color: red;
    border-radius: 55px;
    padding: 10px;
}

a:link {
    text-decoration: none
}
</style>
<header>
        <!-- header inner -->
        <div class="header">

            <div class="container">
                <div class="row">
                    <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col logo_section">
                        <div class="full">
                            <div class="center-desk">
                                <div class="logo">
                                    <a href="{% url 'home' %}"><img src="/static/images/logo.png" alt="#"></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-9 col-lg-9 col-md-9 col-sm-9">
                        <div class="menu-area">
                            <div class="limit-box">
                                <nav class="main-menu">
                                    <ul class="menu-area-main">
                                        <li class="active"> <a href="{% url 'home' %}">Home</a> </li>
                                        <li> <a href="{% url 'about' %}">About</a> </li>
                                        <li><a href="{% url 'brand' %}">Brand</a></li>
                                        <li><a href="{% url 'specials' %}">Specials</a></li>
                                        <li><a href="{% url 'ecomapp:mycart' %}"><i class="fa fa-shopping-cart" style="font-size: 40px;"><span class="top-0 start-10 translate-middle badge rounded-pill bg-danger"></span></i></a></li>
                                        <div class="d-flex justify-content-center h-100">
                                        <div class="search"> 
                                        <form action="{% url 'search-venues' %}" method="POST">
                                            {% csrf_token %}
                                            <input type="text" class="search-input" placeholder="Search..." name="searched"><button style="background-color: red; color: white; padding: 5px; padding-left: 15px; padding-right: 15px;"><i class="fa fa-search"></i></button> </form> 
                                        </div>
                                            
</div>
                                        
                                    </ul>
                                </nav>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 offset-md-6">
                        <div class="location_icon_bottum">
                            <ul>
                                <li><img src="/static/icon/call.png" />(+71)9876543109</li>
                                <li><img src="/static/icon/email.png" />demo@gmail.com</li>
                                <li><img src="/static/icon/loc.png" />Location</li>
                                <div class="row d-flex justify-content-center mt-100" style="float: left;">
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- end header inner -->
    </header>


{% block content %}
  
{% endblock content %}


<footer>
        <div id="contact" class="footer">
            <div class="container">
                <div class="row pdn-top-30" style="padding-bottom: 50px;">
                    <div class="col-md-12 ">
                        <div class="footer-box">
                            <div class="headinga">
                                <h3>Address</h3>
                                <span>Healing Center, 176 W Streetname,New York, NY 10014, US</span>
                                <p>(+71) 8522369417
                                    <br>demo@gmail.com</p>
                            </div>
                            <ul class="location_icon">
                                <li> <a href="#"><i class="fa fa-facebook-f"></i></a></li>
                                <li> <a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li> <a href="#"><i class="fa fa-instagram"></i></a></li>

                            </ul>
                            <div class="menu-bottom">
                                <ul class="link">
                                    <li> <a href="{% url 'home' %}">Home</a></li>
                                    <li> <a href="{% url 'about' %}">About</a></li>
                                    
                                    <li> <a href="{% url 'brand' %}">Brand </a></li>
                                    <li> <a href="{% url 'specials' %}">Specials</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>



    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.0.0.min.js' %}"></script>
    <script src="{% static 'js/plugin.js' %}"></script>
    <!-- sidebar -->
    <script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
    <!-- javascript -->
    <script src="{% static 'js/owl.carousel.js' %}"></script>
    <script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
    <script>
        $(document).ready(function() {
            $(".fancybox").fancybox({
                openEffect: "none",
                closeEffect: "none"
            });

            $(".zoom").hover(function() {

                $(this).addClass('transition');
            }, function() {

                $(this).removeClass('transition');
            });
        });
    </script>
    
  </body>
</html>

shop.net/shopstore/templates/checkout.html
{% extends 'base.html' %}
{% block title %} Added to Cart{% endblock title %}

{% block content %}

<style type="text/css">
	input {
	width: 100%; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; border: 0 red solid; background-color: rgba(0, 0, 0, 0.06); border-left: 3px solid red; border-radius: 5px; color: #666666; font-weight: 300; font-size: 15px; line-height: 24px;
	}
</style>


<div style="padding-top: 10%; padding-bottom: 10%; padding-left: 10%;">
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h3>Items in the cart</h3>
            <a href="{% url 'ecomapp:mycart' %}"><button style="padding: 10px; padding-left: 30px; padding-right: 30px; background-color: red; color: white; border-radius: 5px;">Update</button></a>
            <hr>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Product</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.name}}</td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right">Total</th>
                        <th>$. {{cart.total}}</th>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-md-6">
            <h3>Checkout Form</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
            </form>
            <a href="{% url 'home' %}"><button style="padding: 10px; padding-left: 30px; padding-right: 30px; background-color: red; color: white; border-radius: 5px; float: right;">Place Order</button></a>
        </div>
    </div>
</div>
</div>


{% endblock content %}

shop.net/shopstore/templates/detail.html
{% extends 'base.html' %}

{% block title %} Detail {% endblock title %}

{% block content %}

<style type="text/css">
</style>
<div style="margin-top: 10%; margin-bottom: 10%; margin-left: 25%; width: 50%;">
	<div style="display: inline-block; background-color: #BDBEBE; height: 250px; width: 250px; border: 3px solid red; border-radius: 5px;">
		<img src="{{ product.image.url }}" style="width:80%; margin: 10%;">
	</div>
	<div style="display: inline-block; margin-left: 5%;">
		<h2>Cost:  <span class="badge bg-warning text-light">${{ product.cost }}</span></h2>
		<h2>Created at:  {{ product.made_year }}</h2>
		<h2>Made in:  {{ product.firma }}</h2>
	</div>
	<hr>
	<div>
		<div style="display: inline-block;">
			{% if product.colour == 'red' %}
				<h1 style="font-size: 30px;">{{ product.name }} - <span class="badge bg-danger">{{ product.colour }}</span></h1>
			{% elif product.colour == 'yellow' %}
				<h1 style="font-size: 30px;">{{ product.name }} - <span class="badge bg-warning text-light">{{ product.colour }}</span></h1>
			{% elif product.colour == 'green' %}
				<h1 style="font-size: 30px;">{{ product.name }} - <span class="badge bg-success">{{ product.colour }}</span></h1>
			{% elif product.colour == 'blue' %}
				<h1 style="font-size: 30px;">{{ product.name }} - <span class="badge bg-primary">{{ product.colour }}</span></h1>
			{% elif product.colour == 'black' %}
				<h1 style="font-size: 30px;">{{ product.name }} - <span class="badge bg-dark">{{ product.colour }}</span></h1>
			{% elif product.colour == 'yellow' %}
				<h1 style="font-size: 30px;">{{ product.name }} - <span class="badge bg-warning text-light">{{ product.colour }}</span></h1>
			{% elif product.colour == 'white' %}
				<h1 style="font-size: 30px;">{{ product.name }} - <span class="badge bg-light text-dark">{{ product.colour }}</span></h1>
			{% else %}
				<h1 style="font-size: 30px;">{{ product.name }} - <span class="badge bg-secondary">{{ product.colour }}</span></h1>
			{% endif %}
			<h3>By Admin</h3>
		</div>
		<div style="display: inline-block; float: right;">
				<a href="{% url 'ecomapp:addtocart' product.id %}"><button style="padding: 20px; background-color: red; color: white; border-radius: 5px;"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart-plus" viewBox="0 0 16 16">
  <path d="M9 5.5a.5.5 0 0 0-1 0V7H6.5a.5.5 0 0 0 0 1H8v1.5a.5.5 0 0 0 1 0V8h1.5a.5.5 0 0 0 0-1H9V5.5z"/>
  <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zm3.915 10L3.102 4h10.796l-1.313 7h-8.17zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
</svg>  Add to Cart</button></a>
		</div>
	</div>
	<hr>
	<p>{{ product.text }}</p>
	<p style="float: right;">{{ product.date }}</p>
	<br>
	<hr>
	<div style="margin-top: 20px;">
		<form action="{% url 'comment_url' product.pk %}" method="POST">
			<input type="text" name="fullname" placeholder="Add your fullname here ..." style="width: 100%; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; border: 0 red solid; background-color: rgba(0, 0, 0, 0.06); border-left: 3px solid red; border-radius: 5px; color: #666666; font-weight: 300; font-size: 15px; line-height: 24px;">
			<textarea style="width: 100%; border-radius: 5px; background-color: rgba(0, 0, 0, 0.06); border: 0 solid red; border-left: 3px solid red; padding-top: 10px; padding-left: 10px; margin-top: 15px;  color: #666666; font-weight: 300; font-size: 15px; line-height: 24px;" rows="5" placeholder="Add your comment here ..." name="text"></textarea>
        		{% csrf_token %}
        	<div style="display: inline-block;">
        		<p>Enter your comment about this product</p>
        		<p style="font-style: italic;">- Writing obscene comments can cause some problems!</p>
        	</div>
        	<div style="display: inline-block; float: right;">
        		<button style="padding: 10px; padding-left: 30px; padding-right: 30px; background-color: red; color: white; border-radius: 5px; float: right;">Submit</button>
        	</div>
        </form>
        <br><br>

<div>
{% for r in product.comment_set.all %}

		<div>
			<h3 style="text-align: left;">{{ r.fullname }} <span style="float: right;  color: #666666; font-weight: 300; font-size: 13px; line-height: 24px;">{{ r.date }}</span></h3>
			<p>{{ r.text }}</p>
			<div style="float: right;">
				<a href="{% url 'comment_update' r.pk %}" style="color: red;"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
  <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
  <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
</svg></a>
			</div>		
		</div>
		<br>
	<hr>
{% empty %}
<h1 style="text-align: center;">Your comment will be first</h1>
{% endfor %}
</div>
	</div>
</div>

<script type="text/javascript">
	document.addEventListener("DOMContentLoaded", function() {

document.getElementById('textarea').onkeyup = function () {
document.getElementById('count').innerHTML = "Characters left: " + (500 - this.value.length);
};

});
</script>

{% endblock content %}

shop.net/shopstore/templates/mycart.html
{% extends 'base.html' %}
{% block title %} My Cart {% endblock title %}

{% block content %}

<div  style="padding-top: 10%; padding-bottom: 10%; padding-left: 25%; width: 100%:">
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h2>Items in my cart :</h2><hr>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Product</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.name}}</td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                        <td>
                            <a href="{% url 'ecomapp:managecart' cp.id %}?action=inc" class="btn btn-primary"> + </a>
                            <a href="{% url 'ecomapp:managecart' cp.id %}?action=dcr" class="btn btn-warning"> - </a>
                            <a href="{% url 'ecomapp:managecart' cp.id %}?action=rmv" class="btn btn-danger"> x </a>
                        </td>
                    </tr>
                    {% empty %}
                        <h1 style="color: #23242A">Your cart empty. You can go to <a href="{% url 'brand' %}">brand</a> page to add products</h1>
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right">Total</th>
                        <th>Rs. {{cart.total}}</th>
                        {% if cart.cartproduct_set.all %}
                        <th><a href="{% url 'ecomapp:emptycart' %}">Empty Cart</a></th>
                        {% endif %}
                    </tr>
                    {% if cart.cartproduct_set.all %}
                    <tr>
                        <th><a href="{% url 'ecomapp:checkout' %}"><button style="padding:10px; background-color: red; color: white; border-radius: 5px;">Checkout</button></a></th>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>
</div>


{% endblock content %}